### ISSUE TITLE
File.contents type

### ISSUE THREAD

**Issue by roll** [majodev/metalsmith-headings-identifier#4]
Hi. 

I get "File.contents can only be a Buffer, a Stream, or null".

May be we have to use Buffer here?

```
data.contents = new Buffer($.html());
```

https://github.com/segmentio/metalsmith-markdown/blob/master/lib/index.js#L38

**Comment by oupala** [comment]
:+1: for fixing this issue !

**Comment by majodev** [comment]
Sorry this issue took so long to resolve. Publish to npm as v0.0.5

**Comment by oupala** [comment]
I confirm that the issue is fixed.

Thank you @majodev !
