### ISSUE TITLE
generate unique ids

### ISSUE THREAD

**Issue by oupala** [majodev/metalsmith-headings-identifier#6]
metalsmith-headings-identifier generates headings identifier from headings in the page.

I'm using metalsmith-markdown to generate html from markdown.

What headings identifier would be generated by the following markdown:

```md
# title A

blablabla

## subtitle

blablabla

# title B

blablabla

## subtitle

blablabla
```

Both `subtitles` will have the same id, it will hence be impossible to generate a link to the second anchor.

I've seen on another CMS that ids were appended a number if there was multiple instances of the same id:

```
<h1 id="title_a">title A</h1>
<h2 id="subtitle_1">subtitle</h2>
<h1 id="title_b">title B</h1>
<h2 id="subtitle_2">subtitle</h2>
```

It is a good thing to ensure each anchor is unique.

**Comment by majodev** [comment]
Still on the radar - sorry for the late response...

**Comment by oupala** [comment]
Thanks @majodev for this fix.

It is almost working.

The only thing is that using the index for anchor naming produces strange ids.

With metalsmith-headings-identifier v0.0.8, the example above will produce the following result:

```html
<h1 id="title_a">title A</h1>
<h2 id="subtitle">subtitle</h2>
<h1 id="title_b">title B</h1>
<h2 id="subtitle_3">subtitle</h2>
```

As you can see, the first subtitle won't have any suffix at all, while the second subtitle will have the `_3` suffix.

Anyone will try to locate `subtitle_2` and maybe `subtitle_1`.

I think it would be a good idea to use separate indexes.

**Comment by oupala** [comment]
Thanks @majodev this release is far better than the previous one.

It does now generate the following html:

```html
<h1 id="title_a">title A</h1>
<h2 id="subtitle">subtitle</h2>
<h1 id="title_b">title B</h1>
<h2 id="subtitle_1">subtitle</h2>
```

This is also a bit inconsistent as we can expect `subtitle_1` to be the first subtitle whereas it is actually the second.

I would propose another evolution which could consist in generating on of the following html:

```html
<h1 id="title_a">title A</h1>
<h2 id="subtitle">subtitle</h2>
<h1 id="title_b">title B</h1>
<h2 id="subtitle_2">subtitle</h2>
```

or

```html
<h1 id="title_a">title A</h1>
<h2 id="subtitle_1">subtitle</h2>
<h1 id="title_b">title B</h1>
<h2 id="subtitle_2">subtitle</h2>
```

In my first proposal, the first duplicate title is suffixed with `_2` (instead of `_1`).

The second proposal is even better where the original title is back-modified and also suffixed with `_1`.
